### ISSUE TITLE
Error when exec training = np.array(training)

### ISSUE THREAD

**Issue by sohaibbennasr** [Abdullahw72/E-Commerce-Chatbot#1]
Hi 
i'm facing this problem when running the program

Traceback (most recent call last):
  File "C:\Users\S9924328\SGBDF\HACKATON\PROJECTS\E-Commerce-Chatbot\E-Commerce Chatbot\E-BOT.py", line 76, in <module>
    training = np.array(training)
               ^^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (105, 2) + inhomogeneous part.

can you help me please

My program :

import nltk

from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
import json
import pickle

import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout
from keras.optimizers import SGD
import random

words=[]
classes = []
documents = []
ignore_words = ['?', '!']
data_file = open('intents.json').read()
intents = json.loads(data_file)

for intent in intents['intents']:
    for pattern in intent['patterns']:

       
        w = nltk.word_tokenize(pattern)
        words.extend(w)
      
        documents.append((w, intent['tag']))

       
        if intent['tag'] not in classes:
            classes.append(intent['tag'])

words = [lemmatizer.lemmatize(w.lower()) for w in words if w not in ignore_words]
words = sorted(list(set(words)))

classes = sorted(list(set(classes)))

print (len(documents), "documents")

print (len(classes), "classes", classes)

print (len(words), "unique lemmatized words", words)

pickle.dump(words,open('words.pkl','wb'))
pickle.dump(classes,open('classes.pkl','wb'))

training = []

output_empty = [0] * len(classes)

for doc in documents:

    bag = []

    pattern_words = doc[0]

    pattern_words = [lemmatizer.lemmatize(word.lower()) for word in pattern_words]

    for w in words:
        bag.append(1) if w in pattern_words else bag.append(0)

    output_row = list(output_empty)
    output_row[classes.index(doc[1])] = 1

    training.append([bag, output_row])

random.shuffle(training)
training = np.array(training)

train_x = list(training[:,0])
train_y = list(training[:,1])
print("Training data created")

random.shuffle(training)
training = np.array(training)

train_x = list(training[:,0])
train_y = list(training[:,1])
print("Training data created")

**Comment by Abdullahw72** [comment]
Hi sohaib, I am looking into this error now and will get back to you.

**Comment by Abdullahw72** [comment]
@sohaibbennasr The issue has been fixed. Clone the master branch now, set-up a virtual environment, and install requirements.txt. Then run the code using this env in jupyter notebook. 
If you need help with accessing that kernel in jupyter, follow this guide: https://janakiev.com/blog/jupyter-virtual-envs/
